spring:
    datasource:
        #postgresql connection config
        #url: jdbc:postgresql://localhost:5432/hotelreservationsystemdb
        #username: postgres
        #password: postgres

        #h2 database
        url: jdbc:h2:mem:hotelreservationsystemdb
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        #properties:
            #hibernate:
                #dialect: org.hibernate.dialect.PostgreSQLDialect #postgresql dialect
    
    #enable colors in terminal
    output:
        ansi:
            enabled: always

server:
    port: 8282

#setting pkg's logging level
logging:
    level:
        com:
            collab: debug